name: Despliegue Automático en Servidor UNSA

on:
  push:
    branches:
      - main  # Se ejecutará cada vez que envíes cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Código de GitHub
      uses: actions/checkout@v3

    - name: Desplegar vía SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/cultura/wp-content/themes/futuretheme
          git pull origin main
